name: octopus
description: >
  Highly scalable Flutter starter kit, designed with an optimal predefined structure 
  and inclusive of libraries that are widely applicable in numerous use cases.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=3.10.5 <4.0.0"

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter
  collection: any
  async: any
  meta: any

  # Localization
  intl: 0.18.0
  flutter_localizations:
    sdk: flutter

  # Stream
  stream_transform: 2.1.0
  rxdart: 0.27.7

  # BLoC
  flutter_bloc: 8.1.3

  # Persisting
  shared_preferences: 2.2.0

  # Logging
  stack_trace: 1.11.0
  sentry_flutter: 7.9.0
  logging: 1.2.0

  # Utils
  pure: 0.2.0
  platform_info: 4.0.2
  bloc_concurrency: 0.2.2
  path: 1.8.3
  path_provider: 2.0.15
  
dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter

  # Lints
  sizzle_lints: 2.0.1

  # Utils
  flutter_launcher_icons: 0.13.1
  flutter_native_splash: 2.3.1
  flutter_gen_runner: 5.3.1
  solid_lints: ^0.0.15

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

flutter_gen:
  output: lib/src/core/assets/generated
  line_length: 80
